### ISSUE TITLE
must be of type Response, JsonResponse returned

### ISSUE THREAD

**Issue by jsznap** [GeneaLabs/nova-horizon#10]
Getting this error when trying to utilize this on nova 4. 

`GeneaLabs\NovaHorizon\Http\Middleware\Authorize::handle():` Return value must be of type Illuminate\Http\Response, Illuminate\Http\JsonResponse returned

**Comment by mikebronner** [comment]
@jsznap Thanks for reporting this. By any chance would you be able to submit a PR that fixes this? I'm currently unable to test this in Nova 4.
