### ISSUE TITLE
Nice Package! How to use ??

### ISSUE THREAD

**Issue by santutu** [GeneaLabs/nova-horizon#3]

**Comment by mikebronner** [comment]
1. `composer require genealabs/nova-horizon`
2. Add to Tools section of NovaServiceProvider:
  ```php
  new GeneaLabs\NovaHorizon\NovaHorizon,
  ```

**Comment by mikebronner** [comment]
I will update documentation ... sorry about not having that there yet.

**Comment by xoco70** [comment]
I had to include `new \GeneaLabs\NovaHorizon\NovaHorizon`, with a blackslash first.

**Comment by mikebronner** [comment]
I usually include the use statement at the top, that way you don't need the preceding slash:
```php
use GeneaLabs\NovaHorizon\NovaHorizon;
// ...
new NovaHorizon,
// ...
```

**Comment by mikebronner** [comment]
Updated documentation. Sorry about that. Let me know if you still have questions.
